### PR TITLE
[Design] Add a solution to Implement Trie

### PR DESCRIPTION
**Pull request by wqfan**

### CODE REVIEW

**Comment by soapyigu** [comment]
Hi seems you have conflicts. Could you take a look and resolve them?

**Comment by wqfan** [comment]
> Hi seems you have conflicts. Could you take a look and resolve them?

Resolved conflicts by merging the latest to my branch.

**Comment by wqfan** [comment]
Would you like to take a look and merge this PR by any chance? It has been open for more than 2 months......

**Comment by soapyigu** [comment]
Hi Sorry for the delay, could you resolve the conflicts in README file?

**Comment by wqfan** [comment]
Apologize that it seems I mistakenly deleted my fork. Created a new PR [here](https://github.com/soapyigu/LeetCode-Swift/pull/259) and closing this one.

**Pull request closed without merging**
