### PR TITLE
Optimize solution to Decode String & LRU Cache

### PR DESCRIPTION
**Pull request by iHackSubhodip**
Runtime: 8 ms, faster than 100.00% of Swift online submissions for Decode String.
Memory Usage: 20.1 MB, less than 100.00% of Swift online submissions for Decode String.

### CODE REVIEW

**Comment by soapyigu** [comment]
Looks pretty good. Thanks for adding this. Could you please also update progress session in README file?

**Comment by iHackSubhodip** [comment]
I have changed it to 273. Still there is a conflict, can you resolve that?

**Comment by soapyigu** [comment]
There is a conflict to resolve first.

**Comment by iHackSubhodip** [comment]
Now please check.

**Comment by soapyigu** [comment]
Hi still there are some conflicts in README file. Could you resolve them?

**Comment by iHackSubhodip** [comment]
Ok. Please review my changes.

**Comment by soapyigu** [comment]
Thanks!

**Comment by iHackSubhodip** [comment]
@soapyigu now two LRU Cache solution exists in the repo. Please review.

1. https://github.com/soapyigu/LeetCode-Swift/blob/master/LinkedList/LRUCache.swift
2. https://github.com/soapyigu/LeetCode-Swift/blob/master/Design/LRUCache.swift

**Pull request merged**
