### PR TITLE
Restructured version for Jump Game, Solution for SortArrayByParity and Fix for Spiral Matrix.

### PR DESCRIPTION
**Pull request by iHackSubhodip**

### CODE REVIEW

**Comment by soapyigu** [comment]
What is the point of this restructure work?

**Comment by iHackSubhodip** [comment]
Added solution for "SortArrayByParity"
[https://leetcode.com/problems/sort-array-by-parity]

**Comment by soapyigu** [comment]
Thanks for adding this!

**Comment by iHackSubhodip** [comment]
@soapyigu , Thanks for merging my commits. Looking forward to committing more. :)

**Pull request merged**
